---
kind: Pod
apiVersion: v1
metadata:
  name: gradiusbot-rnd
spec:
  containers:
    - name: gradiusbot-rnd
      image: gradiuscypher/gradiusbot-rnd:arm64
      imagePullPolicy: Always
      volumeMounts:
        - name: config-vol
          mountPath: /discord_gradiusbot/conf
        - name: persist
          mountPath: /discord_gradiusbot/persist
  imagePullSecrets:
    - name: regcred
  restartPolicy: Always
  volumes:
    - name: config-vol
      configMap:
        name: gradiusbot-rnd
    - name: persist
      persistentVolumeClaim:
        claimName: gradiusbot-persist
